apiVersion: v1
kind: Secret
metadata:
  name: j2ee-test-db-secret
data:
  username: dGVzdHVzZXI=
  password: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: j2ee-rest-db
  labels:
    app: j2ee-rest-db
spec:
  replicas: 1
  selector:
    matchLabels:
       app: j2ee-rest-db
  template:
    metadata:
      labels:
        app: j2ee-rest-db
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - name: mariadb
          containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
           secretKeyRef:
             name: j2ee-test-db-secret
             key: username
        - name: MYSQL_PASSWORD
          valueFrom:
           secretKeyRef:
             name: j2ee-test-db-secret
             key: password
        - name: MYSQL_DATABASE
          value: test 
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: j2ee-rest-db
spec:
  selector:
    app: j2ee-rest-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: j2ee-rest-web
  labels:
    app: j2ee-rest-web
spec:
  replicas: 2
  selector:
    matchLabels:
       app: j2ee-rest-web
  template:
    metadata:
      labels:
        app: j2ee-rest-web
    spec:
      containers:
      - name: web
        image: mysinmyc/java-sample-j2ee-rest:mariadb
        ports:
        - containerPort: 9080
        env:
        - name: MYSQL_USER
          valueFrom:
           secretKeyRef:
             name: j2ee-test-db-secret
             key: username
        - name: MYSQL_PASSWORD
          valueFrom:
           secretKeyRef:
             name: j2ee-test-db-secret
             key: password
        - name: MYSQL_DATABASE
          value: test 
        - name: MYSQL_HOST
          value: j2ee-rest-db
---
apiVersion: v1
kind: Service
metadata:
  name: j2ee-rest-web
spec:
  selector:
    app: j2ee-rest-web
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: j2ee-rest-web
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
#  backend:
#   serviceName: j2ee-rest-web
#   servicePort: 9080
  rules:
  - host: "j2eerest.example.com"
    http:
      paths:
      - path: /j2ee-rest
        backend:
          serviceName: j2ee-rest-web
          servicePort: 9080
      - path: /openapi
        backend:
          serviceName: j2ee-rest-web
          servicePort: 9080
