INSERT INTO CONTACT(ID,NAME,ADDRESS,NUMBER) VALUES(1,'CIAO','CIAO','CIAO');
INSERT INTO CONTACT(ID,NAME,ADDRESS,NUMBER) VALUES(2,'MIAO','MIAO','MIAO');
INSERT INTO CONTACT(ID,NAME,ADDRESS,NUMBER) VALUES(3,'BAU','BAU','BAU');