version: '3'
services:
  web:
    image: mysinmyc/java-sample-spring-mongodb-rest
    deploy: 
       replicas: 2
    ports:
      - 8080:8080
    networks:
    - internalnet
    depends_on:
    - mongodb
  mongodb:
    image: mongo
    networks:
    - internalnet

networks:
   internalnet:
